### ISSUE TITLE
Global options parsing error

### ISSUE THREAD

**Issue by sanchit1591** [dotnet/command-line-api#1371]
Reproducing code #1117, I am facing the same issue.
only dotnet run -g works whereas the intention is for it to work for either dotnet run pizza -g or dotnet run -g pizza.

**Comment by elgonzo** [comment]
I just checked quickly with System.CommandLine version 2.0.0-beta1.21406.1, and the issue is resolved.
Try using the most recent version of System.CommandLine.

**Comment by sanchit1591** [comment]
The latest version that I can see on nuget website is 2.0.0-beta1.21308.1 (and I have the same installed in my program). How to get version 2.0.0-beta1.21406.1 @elgonzo ?

**Comment by sanchit1591** [comment]
I downloaded the prerelease version mentioned by you but I still face the same issue. 
>dotnet run pizza -g
Making the Dough.
Adding the Toppings.
Baking the Pizza.
Serving the Pizza

"Welcome to pizza shop" line is still not showed!

**Comment by elgonzo** [comment]
My apologies. You were right. I don't know what i was smoking and seeing there. Testing again, "_Welcome to pizza shop_" is indeed not printed. :-(

**Comment by elgonzo** [comment]
FYI: I just added a comment to the issue you linked to. I just quote it here once more for convenience:

> Your problem is not related to the global option. The global option is a red herring.
> The problem is rather your code having two command handlers, and your expectation of the two command handlers being invoked.
> 
> As the name "command handler" suggests, the handler is for a command, not for an option. So, if you invoke a command line containing the "pizza" command, then the "pizza" command handler will be invoked. That's what you are seeing happening.
> 
> The behavior observed here is pretty much the same as discussed here #1274

**Comment by jonsequitur** [comment]
Thanks @elgonzo, you're exactly right here. To illustrate:

![image](https://user-images.githubusercontent.com/547415/129979221-f5426a4b-2244-4f30-ad75-6bcd77c81d81.png)

**Comment by nathan-alden-sr** [comment]
It seems like there are global options, but no global _handling_ of options. Global handling would be _very_ useful for options like `--verbosity`, where, e.g., a Serilog `LoggerConfiguration` is configured with the specified minimum log level _before_ the actual commands are processed. Currently, I can't figure out a way to do this.

**Comment by nathan-alden-sr** [comment]
This is a dirty hack, but it works. It handles default values, missing values, and misspelled enum values exactly as you'd expect.
```cs
public static Logger Logger { get; private set; } = default!;

private static async Task<int> Main(string[] args)
{
    RootCommand rootCommand =
        new()
        {
            new DropCommand()
        };

    rootCommand.AddGlobalOption(
        new Option<LogEventLevel>("--verbosity", () => LogEventLevel.Information, "The minimum level of log messages written to the console."));
    rootCommand.Handler = CommandHandler.Create<LogEventLevel>(CreateLogger);

    int index = Array.IndexOf(args, "--verbosity");

    if (index > -1)
    {
        await rootCommand.InvokeAsync(args.AsSpan(index, 2).ToArray());
    }
    else
    {
        CreateLogger(LogEventLevel.Information);
    }

    return await rootCommand.InvokeAsync(args);
}

private static void CreateLogger(LogEventLevel verbosity)
{
    LoggerConfiguration configuration = new();

    configuration
        .WriteTo.Console(verbosity, "{Level:u3} {UtcTimestamp} {Message:lj}{NewLine}{Exception}", theme: SystemConsoleTheme.Colored)
        .MinimumLevel.Is(verbosity);

    configuration.Enrich.With<UtcTimestampEnricher>();

    Logger = configuration.CreateLogger();
}
```

**Comment by jonsequitur** [comment]
> It seems like there are global options, but no global handling of options. Global handling would be very useful for options like --verbosity, where, e.g., a Serilog LoggerConfiguration is configured with the specified minimum log level before the actual commands are processed. Currently, I can't figure out a way to do this.

Have you looked into middleware? It sounds like what you're describing. 

![image](https://user-images.githubusercontent.com/547415/140825737-8587c17e-a07e-428c-85db-db395f061550.png)
