### ISSUE TITLE
Add way to enable help command on subcommands

### ISSUE THREAD

**Issue by ThadHouse** [dotnet/command-line-api#758]
Currently, I can not find a way to add automatic help generation to subcommands. This would be very helpful to have.

**Comment by jonsequitur** [comment]
The way that help works is contextual, just like `dotnet`, so you should be able to see that help by doing this:

```console
> rootcommand subcommand -h
```

**Comment by snmed** [comment]
Hi
I know this issue is closed, but I've the same problem. If I doing this
```
rootcommand subcommand -h
```
I get this:
```
'--help' was not matched. Did you mean '--file', or '--url'?
'--help' was not matched. Did you mean '--file', or '--url'?
```
and the help for that option, but this is really ugly. Any suggestions?

**Comment by KathleenDollard** [comment]
@snmed 

This should work, so let's figure out why it doesn't. :-) I'm reopening. 

Starting with the super basic stuff 

- What version of the NuGet package are you using? 
- Is this exactly what you typed? IOW, you typed -h and it said it could not find --help?
- What do you mean "and the help for that option"? Does it display that and then also display help, but help that isn't ugly?
- What does "ugly" mean?

Can you paste from when you say "rootcommand subcommand -h" until the output? If this contains sensitive information, please don't paste it, but do a repro that illustrates the problem without sensitive stuff.

**Comment by jonsequitur** [comment]
I wonder if this might be a setup issue. Could you provide a code sample that reproduces the issue?

**Comment by snmed** [comment]
@KathleenDollard 
Currently I using version 2.0.0-beta1.20071.2.

So here my setup more or less (this is only a minimal example, but exactly the same structure as the prod code):
*Commands.cs*
```csharp
using System;
using System.CommandLine;
using System.CommandLine.Builder;
using System.CommandLine.Invocation;
using System.CommandLine.Parsing;
using System.Threading.Tasks;

namespace CmdExample
{
  public static class Commands
  {
    public static CommandLineBuilder CreateRootCommand() => new CommandLineBuilder(new RootCommand("Test client for xyz service."))
   .UseDefaults()
   .UseTypoCorrections()
   .UseSuggestDirective()
   .UseHelp()
   .UseExceptionHandler();

    public static CommandLineBuilder AddServiceVersionCommand(this CommandLineBuilder builder, Func<SharedOptions, Task> handler)
    {
      Command cmd = new Command("info", "Show version of the result service."){
        new Option(new string[]{"--jwt-key", "-j"}, "The symmetric key to create a valid jwt token.") {
                    Argument = new Argument<string>(),
                },
                new Option(new string[]{"--jwt-file", "-f"}, "File that contains a valid jwt token.") {
                    Argument = new Argument<string>(),
                },
                new Option(new string[]{"--skip-ssl", "-i"}, "Skip validation of the endpoint certificate.") {
                    Argument = new Argument<bool>(),
                },
                new Option(new string[]{"--url", "-u"}, "URL of the grpc result service. (default: https://localhost:5001)") {
                    Argument = new Argument<string>(() => "https://localhost:5001")
                }
      };
      cmd.AddValidator(ValidateJwt);
      cmd.Handler = CommandHandler.Create(handler);

      builder.AddCommand(cmd);
      return builder;
    }

    public static CommandLineBuilder AddUploadCommandHandler(this CommandLineBuilder builder, Func<SharedOptions, Task> handler)
    {
      Command cmd = new Command("upload", "Upload data to the result service.") {
                new Option(new string[]{"--jwt-key", "-j"}, "The symmetric key to create a valid jwt token.") {
                    Argument = new Argument<string>(),
                },
                new Option(new string[]{"--jwt-file", "-f"}, "File that contains a valid jwt token.") {
                    Argument = new Argument<string>(),
                },
                new Option(new string[]{"--skip-ssl", "-i"}, "Skip validation of the endpoint certificate.") {
                    Argument = new Argument<bool>(),
                },
                new Option(new string[]{"--url", "-u"}, "URL of the grpc result service. (default: https://localhost:5001)") {
                    Argument = new Argument<string>(() => "https://localhost:5001")
                }
            };

      cmd.AddValidator(ValidateJwt);
      cmd.Handler = CommandHandler.Create(handler);
      builder.AddCommand(cmd);
      return builder;
    }

    private static string ValidateJwt(CommandResult commandResult)
    {
      var jwtKey = commandResult.ValueForOption<string>("--jwt-key");
      var jwtFile = commandResult.ValueForOption<string>("--jwt-file");
      return string.IsNullOrEmpty(jwtFile) && string.IsNullOrEmpty(jwtKey) ? "Option '--jwt-file' or '--jwt-key' is required." : null;
    }
  }
}

```
*Program.cs*
```csharp
using System;
using System.CommandLine.Parsing;
using System.Threading.Tasks;

namespace CmdExample
{
    class Program
    {
        static async Task<int> Main(string[] args)
        {
            var builder = Commands.CreateRootCommand();
            builder.AddUploadCommandHandler(async (SharedOptions options) =>
            {
                await Task.FromResult("Dummy action");
                Console.WriteLine("Hello from upload command");
            });

            // Add service version command
            builder.AddServiceVersionCommand(async (SharedOptions options) =>
            {
                await Task.FromResult("Dummy action");
                Console.WriteLine("Hello from service version command");
            });

            var parser = builder.Build();
            return await parser.Parse(args).InvokeAsync();
        }
    }
}
```
*SharedOptions.cs*
```csharp
namespace CmdExample
{
    public class SharedOptions
    {
        public string JwtKey { get; set; }

        public string JwtFile { get; set; }

        public string Url { get; set; }

        public bool SkipSsl { get; set; }
    }
}
```
And here how I execute the example:
```cmd
C:\PJ\playground\CmdExample
λ dotnet run -- -h
CmdExample:
  Test client for result service.

Usage:
  CmdExample [options] [command]

Options:
  --version    Display version information

Commands:
  upload    Upload data to the result service.
  info      Show version of the result service.


C:\PJ\playground\CmdExample
λ dotnet run -- upload -h
'-h' was not matched. Did you mean '-j', or '-f', or '-i', or '-u'?
'-h' was not matched. Did you mean '-j', or '-f', or '-i', or '-u'?
upload:
  Upload data to the result service.

Usage:
  CmdExample upload [options]

Options:
  -j, --jwt-key <jwt-key>      The symmetric key to create a valid jwt token.
  -f, --jwt-file <jwt-file>    File that contains a valid jwt token.
  -i, --skip-ssl               Skip validation of the endpoint certificate.
  -u, --url <url>              URL of the grpc result service. (default: https://localhost:5001)

C:\PJ\playground\CmdExample
λ dotnet run -- upload --help
'--help' was not matched. Did you mean '--url'?
'--help' was not matched. Did you mean '--url'?
upload:
  Upload data to the result service.

Usage:
  CmdExample upload [options]

Options:
  -j, --jwt-key <jwt-key>      The symmetric key to create a valid jwt token.
  -f, --jwt-file <jwt-file>    File that contains a valid jwt token.
  -i, --skip-ssl               Skip validation of the endpoint certificate.
  -u, --url <url>              URL of the grpc result service. (default: https://localhost:5001)
```
I hope that's enough information, but if you need additional, I'm pleased to provide you with more information.

**Comment by jonsequitur** [comment]
Thanks for the thorough repro!

It appears that this bug was fixed in a more recent version. If you update `System.CommandLine` it should resolve it:

![image](https://user-images.githubusercontent.com/547415/76439193-43ecb380-6379-11ea-8bf7-7f9f345a3be0.png)

**Comment by snmed** [comment]
@jonsequitur Okay that's good to hear, I will try it tomorrow and get back to you if I still have the same problem after updating the package. But I think you can close this issue, as you have already tested the example and it seems to work.

Thank you for the quick response and sorry to not realize that already a newer version was out.

**Comment by jonsequitur** [comment]
No problem. Thanks for the detailed report. Please reopen this if you're still seeing the issue after updating.

**Comment by TraGicCode** [comment]
Hey @jonsequitur ,

Am i using the right version of the latest beta nuget package?

```
 <PackageReference Include="System.CommandLine" Version="2.0.0-beta1.20204.1" />
```

If not what is the correct nuget source i should use?  If so, is this still broken?  I'm getting the same issue as the original pr creator

**Comment by snmed** [comment]
Hi @TraGicCode,
I'm using this version `<PackageReference Include="System.CommandLine" Version="2.0.0-beta1.20158.1" />`, and I know it's working for that version. As far as I can see, it's the latest version of this package. Try to upgrade your package reference and try again, it might work for you as well.

Cheers

**Comment by TraGicCode** [comment]
> Hi @TraGicCode,
> I'm using this version `<PackageReference Include="System.CommandLine" Version="2.0.0-beta1.20158.1" />`, and I know it's working for that version. As far as I can see, it's the latest version of this package. Try to upgrade your package reference and try again, it might work for you as well.
> 
> Cheers

I was using the latest package from the nuget.org feed but still no luck!

**Comment by snmed** [comment]
Strange, I don't see your mentioned release, but maybe I get another page in Switzerland than you guys in the US. And if you really have a newer release, then probably the bug is back in that release. Can you try it with the mentioned release above?
![image](https://user-images.githubusercontent.com/5249768/79122794-e9d87700-7d98-11ea-9486-49f651b8d213.png)

**Comment by jonsequitur** [comment]
The most recent versions of the package can be found in this feed:  https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json

The version on nuget.org is manually updated and typically a bit behind, but we'll be updating it shortly.

**Comment by jonsequitur** [comment]
I've just pushed a new version to nuget.org. It should appear momentarily once it's done being indexed.
